export const TOUR_LIST_REQUEST = 'TOUR_LIST_REQUEST';
export const TOUR_LIST_SUCCESS = 'TOUR_LIST_SUCCESS';
export const TOUR_LIST_FAIL = 'TOUR_LIST_FAIL';

export const TOUR_CREATE_REQUEST = 'TOUR_CREATE_REQUEST';
export const TOUR_CREATE_SUCCESS = 'TOUR_CREATE_SUCCESS';
export const TOUR_CREATE_FAIL = 'TOUR_CREATE_FAIL';

export const TOUR_SAVE_REQUEST = 'TOUR_SAVE_REQUEST';
export const TOUR_SAVE_SUCCESS = 'TOUR_SAVE_SUCCESS';
export const TOUR_SAVE_FAIL = 'TOUR_SAVE_FAIL';

export const TOUR_DELETE_REQUEST = 'TOUR_DELETE_REQUEST';
export const TOUR_DELETE_SUCCESS = 'TOUR_DELETE_SUCCESS';
export const TOUR_DELETE_FAIL = 'TOUR_DELETE_FAIL';

export const TOUR_TOP5_REQUEST = 'TOUR_TOP5_REQUEST';
export const TOUR_TOP5_SUCCESS = 'TOUR_TOP5_SUCCESS';
export const TOUR_TOP5_FAIL = 'TOUR_TOP5_FAIL';

export const TOUR_DETAILS_REQUEST = 'TOUR_DETAILS_REQUEST';
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS';
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL';